Repository lucasvillarinho/nofy, pull requests merged in 2024-08, with the labels that each got.

#2 feat: New Readme
  .pre-commit-config.yaml
  LICENSE
  Makefile
  README.md
  cmd/.gitkeep
Labels: documentation

#3 fix: bug in example code in README
  README.md
Labels: documentation

#4 Feat/update readme
  .gitignore
  CODE_OF_CONDUCT.md
  README.md
  docs/images/logo.png
Labels: documentation

#8 fix: Codecov
  .github/workflows/codecov.yml
Labels: bug, Actions

#10 feat: Add Golang workflow
  .github/workflows/codecov.yml
  .github/workflows/golang.yml
Labels: Actions

#11 feat: Create helper to make a generic HTTP request
  Makefile
  helpers/assert/assert_test.go
  helpers/request/request.go
  helpers/request/request_mock.go
  helpers/request/request_test.go
  messengers/slack/slack.go
  messengers/slack/slack_test.go
  nofy.go
  nofy_test.go
Labels: core
